platform :ios, '13.0'

target 'Shopertino' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!

  # Pods for Shopertino
  pod 'FacebookCore', '=  0.9.0'
  pod 'FacebookLogin', '=  0.9.0'
  pod 'FacebookShare', '=  0.9.0'

  pod 'Firebase/Core', '=  7.6.0'
  pod 'Firebase/Auth', '=  7.6.0'
  pod 'Firebase/Database', '=  7.6.0'
  pod 'Firebase/Storage', '=  7.6.0'
  pod 'Firebase/Firestore', '=  7.6.0'
  pod 'Firebase/Messaging', '=  7.6.0'

  pod 'Alamofire', '=  5.4.1'
  pod 'Kingfisher', '=  6.1.0'
  pod 'Stripe', '=  21.2.0'
  pod 'Eureka', '=  5.3.2'
  pod 'GooglePlaces', '=  3.9.0'
  pod 'GoogleMaps', '= 3.9.0'
end
